### ISSUE TITLE
[BUG] - cant select anything

### ISSUE THREAD

**Issue by Profoundant89** [eastcw/foundryvtt-dnd5eCharacterActions#10]
**Describe the bug**
none of the actions listed in the action tab are actually selectable, i only noticed this working after the dnd beyond merger, but i also hadnt played in like a month. 

**To Reproduce**
If there are any specific steps needed to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Version**
using the latest stable version.

**Comment by eastcw** [comment]
This has been caused by the new 5e 3.0 system release and should be fixed by the next release. Sorry for the wait!
