### ISSUE TITLE
[BUG] Actions tab empty in default dnd5e 3.0.x character sheet

### ISSUE THREAD

**Issue by Geektasticdad** [eastcw/foundryvtt-dnd5eCharacterActions#12]
**Describe the bug**
It seems the actions are not populated in the "Actions" tab of the new dnd5e 3.0.x game system.

**To Reproduce**
1. Edit a character
2. Add items to "actions"
3. Check actions tab

**Expected behavior**
Actions tab to be populated

**Screenshots**
![chrome_6XbgjYQ3MO](https://github.com/eastcw/foundryvtt-dnd5eCharacterActions/assets/73676044/a1c8ab92-4224-4f57-ba63-c4150c5db792)

![chrome_AUI6s7Wxbl](https://github.com/eastcw/foundryvtt-dnd5eCharacterActions/assets/73676044/abeca43d-40d9-4cb6-9458-78f4f44785ca)

**Version**
Foundry 11.315
DND5e 3.0.3
Character Actions List dnd53 6.1.1

**Comment by d20an** [comment]
This is fixed in my pull request: https://github.com/eastcw/foundryvtt-dnd5eCharacterActions/pull/11
